GitHub Actions: Docusaurus: Check links and anchors

diff --git a/.github/workflows/docusaurus.yaml b/.github/workflows/docusaurus.yaml
--- a/.github/workflows/docusaurus.yaml
+++ b/.github/workflows/docusaurus.yaml
@@ -98,55 +98,68 @@ jobs:
         with:
           path: docusaurus/build
           key: ${{ github.ref }}-docusaurus-build
-      - name: Install hyperlink
-        if: github.event_name != 'workflow_dispatch'
-        run: npm install -g @untitaker/hyperlink
       - name: Install dependencies
         run: npm install
         working-directory: ./docusaurus
       - name: Install js-api dependencies
         run: npm install
         working-directory: ./js-api
-      - name: Build Docusaurus website
-        run: npm run build
-        working-directory: ./docusaurus
-      - name: Lint-Fix Markdown
-        run: |
-          npm install -g markdownlint-cli2
-          markdownlint-cli2-fix "help/**/*.{md,mdx}" > help/_lint-check-report.md 2>&1
+      - run: npm run lint > help/_lint-check-report.md 2>&1
         continue-on-error: true
         if: github.event_name != 'workflow_dispatch' && needs.lint.outputs.result != 'success'
-      - name: Check anchors
-        id: anchors
-        working-directory: ./docusaurus
-        if: github.event_name != 'workflow_dispatch'
-        continue-on-error: true
+      - name: Build Docusaurus website
+        id: build
         run: |
-          hyperlink --check-anchors build/ --sources ../help/ > ../help/_anchor-check-report.md 2>&1
+          npm run build > ../help/_docusaurus_build.txt 2>&1
           echo "result=success" >> $GITHUB_OUTPUT
+        working-directory: ./docusaurus
+        continue-on-error: true
       - name: Set summary
+        id: build_summary
         if: github.event_name != 'workflow_dispatch'
         continue-on-error: true
         run: |
-          echo "## Summary" >  "${GITHUB_STEP_SUMMARY}"
-          if [[ "${{ steps.anchors.outputs.result }}" == "success" ]]; then
+          echo "## Summary" > "${GITHUB_STEP_SUMMARY}"
+          if [[ "${{ steps.build.outputs.result }}" == "success" ]]; then
             echo ":white_check_mark: Successful" >> "${GITHUB_STEP_SUMMARY}"
           else
             echo ":no_entry_sign: Some errors occurred" >> "${GITHUB_STEP_SUMMARY}"
-            echo ":no_entry_sign: Hyperlink link checker errors:"
-            echo "To test locally use the [instructions](https://datagrok.ai/help/develop/help-pages/github-workflow#links-and-anchors-check)" >> help/_anchor-check-report.md
-            cat help/_anchor-check-report.md >> "${GITHUB_STEP_SUMMARY}"
-            cat help/_anchor-check-report.md
-            sed -i '/Found some broken links, reading source files/a ## Errors per input' ${GITHUB_STEP_SUMMARY}
-            sed -i -r 's,^(help/.*\.md)$,### \1,g' ${GITHUB_STEP_SUMMARY}
-            sed -i 's,error:,**Error:**,g' ${GITHUB_STEP_SUMMARY}
-            sed -i -r 's,(at line [0-9]+),**\1**,g' ${GITHUB_STEP_SUMMARY}
-            sed -i -r 's,^(output/help.*\.html)$,### \1,g' ${GITHUB_STEP_SUMMARY}
-            sed -i -r '/^Found [0-9]+ bad links/i ## Errors summary' ${GITHUB_STEP_SUMMARY}
-            sed -i -r '/^To test locally use the .*/i ## Local execution' ${GITHUB_STEP_SUMMARY}
-            exit 1
+            bash docusaurus/broken_links.sh help/_docusaurus_build.txt help/broken_links.csv
+            line_count=$(wc -l < help/broken_links.csv)
+
+            echo "## Local execution" >> ${GITHUB_STEP_SUMMARY}
+            echo "To test locally run 'npm run build' from docusaurus directory" >> ${GITHUB_STEP_SUMMARY}
+
+            if [ "$line_count" -gt 1 ]; then
+              echo "## Broken links" >> ${GITHUB_STEP_SUMMARY}
+              # Add CSV as Markdown table 
+              echo "|$(head -n 1 help/broken_links.csv | sed 's/,/|/g')|" | sed -e 's/|"/|/g' -e 's/"|/|/g' >> ${GITHUB_STEP_SUMMARY}
+              echo "|$(head -n 1 help/broken_links.csv | sed 's/[^,]/-/g' | sed 's/,/|/g')|" >> ${GITHUB_STEP_SUMMARY}
+              tail -n +2 help/broken_links.csv | sed 's/,/|/g' | sed 's/^/|/' | sed 's/$/|/' | sed -e 's/|"/|/g' -e 's/"|/|/g' >> ${GITHUB_STEP_SUMMARY}
+
+              echo "broken_links=true" >> $GITHUB_OUTPUT
+            else
+              echo "## Build output" >> ${GITHUB_STEP_SUMMARY}
+              cat help/_docusaurus_build.txt >> "${GITHUB_STEP_SUMMARY}"
+              echo ":no_entry_sign: Docusaurus build errors:"
+              cat help/_docusaurus_build.txt
+            fi
+
+            if [[ "${{ steps.build.outcome }}" == "failure" ]]; then
+                exit 1
+            else
+                echo ':warning: Ignored docusaurus build warnings'
+            fi
           fi
       - uses: actions/upload-artifact@v2
+        name: Save broken links report
+        if: always() && steps.build_summary.outputs.broken_links == 'true'
+        with:
+          name: broken_links.csv
+          path: help/broken_links.csv
+          retention-days: 14
+      - uses: actions/upload-artifact@v2
+        name: Save docusaurus build
         if: github.ref == 'refs/heads/master' && steps.anchors.outputs.result == "success"
         with:
           name: docusaurus
