GitHub Actions: Docusaurus: Summary report fix

diff --git a/.github/workflows/docusaurus.yaml b/.github/workflows/docusaurus.yaml
--- a/.github/workflows/docusaurus.yaml
+++ b/.github/workflows/docusaurus.yaml
@@ -110,49 +110,48 @@ jobs:
       - name: Build Docusaurus website
         id: build
         run: |
-          set -x
           npm run build > ../help/_docusaurus_build.txt 2>&1
-          echo "result=success" >> $GITHUB_OUTPUT
         working-directory: ./docusaurus
         continue-on-error: true
       - name: Set summary
         id: build_summary
         run: |
-          set -x
           echo "## Summary" > "${GITHUB_STEP_SUMMARY}"
-          if [[ "${{ steps.build.outputs.result }}" == "success" ]]; then
-            echo ":white_check_mark: Successful" >> "${GITHUB_STEP_SUMMARY}"
+
+          bash docusaurus/broken_links.sh help/_docusaurus_build.txt help/_broken_links.csv
+          if [ -f help/_broken_links.csv ]; then
+            line_count=$(wc -l < help/broken_links.csv)
           else
-            echo ":no_entry_sign: Some errors occurred" >> "${GITHUB_STEP_SUMMARY}"
-            bash docusaurus/broken_links.sh help/_docusaurus_build.txt help/_broken_links.csv
-            if [ -f help/_broken_links.csv ]; then
-              line_count=$(wc -l < help/broken_links.csv)
-            else
-              line_count=0
-            fi
+            line_count=0
+          fi
 
-            echo "## Local execution" >> ${GITHUB_STEP_SUMMARY}
-            echo "To test locally run 'npm run build' from docusaurus directory" >> ${GITHUB_STEP_SUMMARY}
+          if [ "$line_count" -gt 1 ] || [[ "${{ steps.build.outcome }}" == "failure" ]] ; then
+              echo ":no_entry_sign: Some errors occurred" >> "${GITHUB_STEP_SUMMARY}"
 
-            if [ "$line_count" -gt 1 ]; then
-              echo "## Broken links" >> ${GITHUB_STEP_SUMMARY}
-              # Add CSV as Markdown table 
-              echo "|$(head -n 1 help/_broken_links.csv | sed 's/,/|/g')|" | sed -e 's/|"/|/g' -e 's/"|/|/g' >> ${GITHUB_STEP_SUMMARY}
-              echo "|$(head -n 1 help/_broken_links.csv | sed 's/[^,]/-/g' | sed 's/,/|/g')|" >> ${GITHUB_STEP_SUMMARY}
-              tail -n +2 help/_broken_links.csv | sed 's/,/|/g' | sed 's/^/|/' | sed 's/$/|/' | sed -e 's/|"/|/g' -e 's/"|/|/g' >> ${GITHUB_STEP_SUMMARY}
-              echo "broken_links=true" >> $GITHUB_OUTPUT
-            else
-              echo "## Build output" >> ${GITHUB_STEP_SUMMARY}
-              cat help/_docusaurus_build.txt >> "${GITHUB_STEP_SUMMARY}"
-              echo ":no_entry_sign: Docusaurus build errors:"
-              cat help/_docusaurus_build.txt
-            fi
+              echo "## Local execution" >> ${GITHUB_STEP_SUMMARY}
+              echo "To test locally run 'npm run build' from docusaurus directory" >> ${GITHUB_STEP_SUMMARY}
 
-            if [[ "${{ steps.build.outcome }}" == "failure" ]]; then
-                exit 1
-            else
-                echo ':warning: Ignored docusaurus build warnings'
-            fi
+              if [ "$line_count" -gt 1 ]; then
+                echo "## Broken links" >> ${GITHUB_STEP_SUMMARY}
+                # Add CSV as Markdown table 
+                echo "|$(head -n 1 help/_broken_links.csv | sed 's/,/|/g')|" | sed -e 's/|"/|/g' -e 's/"|/|/g' >> ${GITHUB_STEP_SUMMARY}
+                echo "|$(head -n 1 help/_broken_links.csv | sed 's/[^,]/-/g' | sed 's/,/|/g')|" >> ${GITHUB_STEP_SUMMARY}
+                tail -n +2 help/_broken_links.csv | sed 's/,/|/g' | sed 's/^/|/' | sed 's/$/|/' | sed -e 's/|"/|/g' -e 's/"|/|/g' >> ${GITHUB_STEP_SUMMARY}
+                echo "broken_links=true" >> $GITHUB_OUTPUT
+              else
+                echo "## Build output" >> ${GITHUB_STEP_SUMMARY}
+                cat help/_docusaurus_build.txt >> "${GITHUB_STEP_SUMMARY}"
+                echo ":no_entry_sign: Docusaurus build errors:"
+                cat help/_docusaurus_build.txt
+              fi
+    
+              if [[ "${{ steps.build.outcome }}" == "failure" ]]; then
+                  exit 1
+              else
+                  echo ':warning: Ignored docusaurus build warnings'
+              fi
+          else
+              echo ":white_check_mark: Successful" >> "${GITHUB_STEP_SUMMARY}"
           fi
       - uses: actions/upload-artifact@v2
         name: Save broken links report
