Help: Do not store plugins.json in repository

diff --git a/.github/workflows/docusaurus.yaml b/.github/workflows/docusaurus.yaml
--- a/.github/workflows/docusaurus.yaml
+++ b/.github/workflows/docusaurus.yaml
@@ -35,6 +35,10 @@ on:
       - 'js-api/**'
       - 'help/deploy/releases/plugins/**'
       - 'packages/*/CHANGELOG.md'
+  workflow_run:
+    workflows: [Packages]
+    types: [completed]
+    branches: [master]
 
 jobs:
   common-check:
@@ -199,46 +203,46 @@ jobs:
           name: docusaurus
           path: docusaurus/build
           retention-days: 7
-      - name: Commit plugins.json
-        id: git
-        if: github.ref == 'refs/heads/master'
-        continue-on-error: true
-        run: |
-          git config --global user.name 'github-actions[bot]'
-          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
-          git pull
-          continue=false
-          if [ -n "$(git status -s help/deploy/releases/plugins/)" ]; then
-            git add help/deploy/releases/plugins/
-            skip_ci=""
-            if [ ${{ github.ref }} == 'refs/heads/master' ]; then
-              skip_ci="[skip ci]"
-            fi
-            git commit -m "GitHub Actions: Update plugins.json $skip_ci
-
-            Workflow ${{ github.workflow }} ${{ github.run_number }}
-            https://github.com/datagrok-ai/public/actions/runs/${{ github.run_id }}"
-            continue=true
-          fi
-          if [[ "${continue}" == "true" ]]; then
-            count=0
-            retries=10
-            until git push; do
-              exit=$?
-              wait=$((2 ** count))
-              count=$((count + 1))
-              if [ $count -lt "$retries" ]; then
-                echo "Retry $count/$retries exited $exit, retrying 'git push' in $wait seconds..."
-                sleep $wait
-                git pull --rebase
-              else
-                echo "Retry $count/$retries exited $exit, no more retries left for 'git push'."
-                exit $exit
-              fi
-            done
-          fi
-
-
+#      - name: Commit plugins.json
+#        id: git
+#        if: github.ref == 'refs/heads/master'
+#        continue-on-error: true
+#        run: |
+#          git config --global user.name 'github-actions[bot]'
+#          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+#          git pull
+#          continue=false
+#          if [ -n "$(git status -s help/deploy/releases/plugins/)" ]; then
+#            git add help/deploy/releases/plugins/
+#            skip_ci=""
+#            if [ ${{ github.ref }} == 'refs/heads/master' ]; then
+#              skip_ci="[skip ci]"
+#            fi
+#            git commit -m "GitHub Actions: Update plugins.json $skip_ci
+#
+#            Workflow ${{ github.workflow }} ${{ github.run_number }}
+#            https://github.com/datagrok-ai/public/actions/runs/${{ github.run_id }}"
+#            continue=true
+#          fi
+#          if [[ "${continue}" == "true" ]]; then
+#            count=0
+#            retries=10
+#            until git push; do
+#              exit=$?
+#              wait=$((2 ** count))
+#              count=$((count + 1))
+#              if [ $count -lt "$retries" ]; then
+#                echo "Retry $count/$retries exited $exit, retrying 'git push' in $wait seconds..."
+#                sleep $wait
+#                git pull --rebase
+#              else
+#                echo "Retry $count/$retries exited $exit, no more retries left for 'git push'."
+#                exit $exit
+#              fi
+#            done
+#          fi
+#
+#
   deploy:
     name: Deploy
     needs: [ convert, common-check ]
