GROK-11505 docusaurus (#1496)
* Help: GROK-11505: Docusaurus with datagrok styles

* Help: GROK-11505: Titles in Help for Docusaurus

* Help: GROK-11505: Docusaurus fixes

* Help: GROK-11505: Remove obsolete symbols in titeles

* Help: GROK-11505: preserve js-api docs directory

* Help: GROK-11505: Markdown lint for docusaurus

* Help: GROK-11505: CI/CD to deploy docusaurus

* Help: GROK-11505: JS API README

* GitHub Actions: GROK-11505: Docusaurus deploy on changes in api

* GitHub Actions: GROK-11505: DocSearch scrape on updates in wiki

* Help: GROK-11505: Docusaurus link to the site in the top bar

GitHub Actions: GROK-11505: DocSearch scrape

* GitHub Actions: GROK-11505: typesense-scraper github actions

diff --git a/.github/workflows/help.yaml b/.github/workflows/help.yaml
--- a/.github/workflows/help.yaml
+++ b/.github/workflows/help.yaml
@@ -5,6 +5,9 @@ on:
   push:
     paths:
       - 'help/**'
+      - 'docusaurus/**'
+      - 'js-api/**'
+
 jobs:
   lint:
     name: Lint
@@ -15,124 +18,74 @@ jobs:
       - name: Lint Markdown
         id: check
         uses: docker://ghcr.io/igorshubovych/markdownlint-cli:latest
+        continue-on-error: true
         with:
           args: --output help/lint-check-report.md --config .github/linters/.markdownlint.yaml "help/**/*.md"
       - name: Set summary
-        if: always()
         run: |
           echo "## Summary" >  "${GITHUB_STEP_SUMMARY}"
           if [ -s help/lint-check-report.md ]; then
-            echo ":no_entry_sign: Some errors occured" >> "${GITHUB_STEP_SUMMARY}"
+            echo ":no_entry_sign: Some errors occurred" >> "${GITHUB_STEP_SUMMARY}"
             echo "## Errors per input" >> "${GITHUB_STEP_SUMMARY}"
             cat help/lint-check-report.md >> "${GITHUB_STEP_SUMMARY}"
+            echo ":no_entry_sign: Markdown Linter errors:"
+            cat help/lint-check-report.md
+            echo "To test locally run the following:"
+            echo 'docker run -v $(pwd):/workdir ghcr.io/igorshubovych/markdownlint-cli:latest --config .github/linters/.markdownlint.yaml "help/**/*.md"'
+            exit 1
           else
             echo ":white_check_mark: Successful" >> "${GITHUB_STEP_SUMMARY}"
           fi
 
-  link_check:
-    name: Check links
-    runs-on: ubuntu-20.04
-    steps:
-      - name: Checkout
-        uses: actions/checkout@v3
-      - name: Check Markdown links
-        uses: lycheeverse/lychee-action@76ab977fedbeaeb32029313724a2e56a8a393548
-        env:
-          GITHUB_TOKEN: ${{ secrets.WRITE_TOKEN }}
-        with:
-          args: "--exclude-all-private --require-https --cache -a 429 --verbose --no-progress 'help/**/*.md'"
-          fail: true
-          jobSummary: true
-          format: markdown
-          output: help/link-check-report.md
-
   convert:
     name: Convert to HTML
-    needs: [ lint, link_check ]
+    needs: [lint]
     runs-on: ubuntu-20.04
     steps:
       - name: Checkout
         uses: actions/checkout@v3
-
-      - name: Create Lua Filters for Pandoc
-        run: |
-          cat <<EOT > links-to-html.lua
-          function Link(el)
-            el.target = string.gsub(el.target, "%.md", ".html")
-            return el
-          end
-          EOT
-          cat <<EOT > table-id.lua
-          function Table(el)
-            el.attr.identifier = "help-table"
-            return el
-          end
-          EOT
-      - name: Create entrypoint for Pandoc
-        working-directory: ./help
-        run: |
-          echo '#!/bin/sh' > entrypoint.sh
-          files="$(find . -type f -name '*.md' -not -path "*/_*" -not -name '*-test.md' -printf '%P ')"
-          for f in $files; do
-            if [[ "$(dirname ${f})" == "." ]]; then
-              dir=''
-            else
-              dir=$(dirname "${f}")
-            fi
-            mkdir -p "output/help/${dir}";
-            echo "cd /github/workspace/help/output/help/${dir}" >> entrypoint.sh;
-            echo "pandoc -f gfm -t html --resource-path=.:/github/workspace/help/${dir} --lua-filter=/github/workspace/links-to-html.lua --lua-filter=/github/workspace/table-id.lua --output=/github/workspace/help/output/help/${f/.md/.html} \"/github/workspace/help/${f}\"" >> entrypoint.sh;
-          done;
-          media="$(find . -type f \( -name '*.gif' -o -name '*.jpeg' -o -name '*.jpg' -o -name '*.png' -o -name '*.bmp' \) -printf '%P ')"
-          for m in $media; do
-            if [[ "$(dirname ${m})" == "." ]]; then
-              dir=''
-            else
-              dir=$(dirname "${m}")
-            fi
-            mkdir -p "output/help/${dir}";
-            echo "cp /github/workspace/help/${m} /github/workspace/help/output/help/${m}" >> entrypoint.sh;
-          done;
-      - name: Convert Mardown to HTML
-        uses: docker://pandoc/core:latest
+      - uses: actions/setup-node@v3
         with:
-          entrypoint: /bin/sh
-          args: /github/workspace/help/entrypoint.sh
-      - name: Apply internal styles to HTML which is not supported by pandoc yet
-        working-directory: ./help
-        run: |
-          for f in output/help/**/*.html; do
-            sed -i -e '0,/<p>/s//<p class="d4-help-info">/' "$f";
-          done;
-      - name: Set up Dart SDK
-        uses: dart-lang/setup-dart@v1
+          node-version: 18
+          cache: npm
+          cache-dependency-path: |
+            docusaurus/package-lock.json
+            js-api/package-lock.json
+      - name: Cache Docusaurus
+        uses: actions/cache@v3
         with:
-          sdk: 1.24.3
-      - uses: actions/cache@v1
+          path: docusaurus/.docusaurus
+          key: ${{ github.ref }}-docusaurus
+      - name: Cache Docusaurus build
+        uses: actions/cache@v3
         with:
-          path: /opt/hostedtoolcache/dart-sdk-1.24.3
-          key: dart-1.24.3-install-cache
-      - name: Install Dart dependencies
-        run: pub get
-        working-directory: ./help/_internal
-      - name: Run Dart script to create menu
-        run: dart generate_menu.dart -s ../output/help/ -d ../output/help/
-        working-directory: ./help/_internal
-      - name: Move output HTML files
-        id: move
-        run: mv help/output/ output/
+          path: docusaurus/build
+          key: ${{ github.ref }}-docusaurus-build
       - name: Install anchor-check
         run: npm install -g @untitaker/hyperlink
+      - name: Install dependencies
+        run: npm install
+        working-directory: ./docusaurus
+      - name: Install js-api dependencies
+        run: npm install
+        working-directory: ./js-api
+      - name: Build Docusaurus website
+        run: npm run build
+        working-directory: ./docusaurus
       - name: Check anchors
         id: anchors
+        working-directory: ./docusaurus
+        continue-on-error: true
         run: |
-          hyperlink --check-anchors output/ --sources help/ >  help/anchor-check-report.md 2>&1
+          hyperlink --check-anchors build/ --sources ../help/ >  ../help/anchor-check-report.md 2>&1
+          echo "result=success" >> $GITHUB_OUTPUT
       - name: Set summary
-        if: always() && (steps.anchors.outcome == 'failure' || steps.anchors.outcome == 'success')
         run: |
           echo "## Summary" >  "${GITHUB_STEP_SUMMARY}"
-          if [[ "${{ steps.anchors.outcome }}" == "failure" ]]; then
-            echo ":no_entry_sign: Some errors occured" >> "${GITHUB_STEP_SUMMARY}"
+          if [[ "${{ steps.anchors.outputs.result }}" == "success" ]]; then
+            echo ":white_check_mark: Successful" >> "${GITHUB_STEP_SUMMARY}"
+          else
+            echo ":no_entry_sign: Some errors occurred" >> "${GITHUB_STEP_SUMMARY}"
             cat help/anchor-check-report.md >> "${GITHUB_STEP_SUMMARY}"
             sed -i '/Found some broken links, reading source files/a ## Errors per input' ${GITHUB_STEP_SUMMARY}
             sed -i -r 's,^(help/.*\.md)$,### \1,g' ${GITHUB_STEP_SUMMARY}
@@ -140,16 +93,21 @@ jobs:
             sed -i -r 's,(at line [0-9]+),**\1**,g' ${GITHUB_STEP_SUMMARY}
             sed -i -r 's,^(output/help.*\.html)$,### \1,g' ${GITHUB_STEP_SUMMARY}
             sed -i -r '/^Found [0-9]+ bad links/i ## Errors summary' ${GITHUB_STEP_SUMMARY}
-          else
-            echo ":white_check_mark: Successful" >> "${GITHUB_STEP_SUMMARY}"
+            echo ":no_entry_sign: Hyperlink link checker errors:"
+            cat help/anchor-check-report.md
+            echo "To test locally run the following:"
+            echo 'npm install -g @untitaker/hyperlink'
+            echo 'cd docusaurus'
+            echo 'npm install'
+            echo 'npm run build'
+            echo 'hyperlink --check-anchors build/ --sources ../help/'
+            exit 1
           fi
-
       - name: 'Upload Artifact'
-        if: always() && steps.move.outcome == 'success'
         uses: actions/upload-artifact@v2
         with:
-          name: help_html_pages
-          path: output
+          name: docusaurus
+          path: docusaurus/build
           retention-days: 7
 
   deploy:
@@ -158,14 +116,15 @@ jobs:
     concurrency:
       group: help-deploy-${{ github.ref }}
       cancel-in-progress: true
-    if: github.ref == 'refs/heads/master'
+#    if: github.ref == 'refs/heads/master'
     runs-on: ubuntu-20.04
     environment: Help
     steps:
       - name: Download artifact
         uses: actions/download-artifact@v2
         with:
-          name: help_html_pages
+          name: docusaurus
+          path: docusaurus/build
       - name: Deploy to server
         shell: bash
         run: |
@@ -191,10 +150,31 @@ jobs:
             --itemize-changes \
             --stats \
             --human-readable \
-            "help/" "$REMOTE_USER@$REMOTE_HOST:$TARGET"
+            "docusaurus/build/" "$REMOTE_USER@$REMOTE_HOST:$TARGET"
         env:
           SSH_PRIVATE_KEY: ${{ secrets.HELP_SSH_KEY }}
           SSH_KNOWN_HOSTS: ${{ secrets.HELP_KNOWN_HOST }}
           REMOTE_HOST: ${{ secrets.HELP_HOST }}
           REMOTE_USER: ${{ secrets.HELP_USER }}
           TARGET: ${{ secrets.WIKI_DOCS_TARGET }}
+
+  scrape:
+    name: Scrape
+    needs: deploy
+    environment: Help
+    concurrency:
+      group: help-scrape-${{ github.ref }}
+      cancel-in-progress: true
+    #    if: github.ref == 'refs/heads/master'
+    runs-on: ubuntu-20.04
+    steps:
+      - name: Checkout
+        uses: actions/checkout@v3
+      - name: Update the DocSearch index
+        uses: celsiusnarhwal/typesense-scraper@v2
+        with:
+          api-key: ${{ secrets.TYPESENSE_API_KEY }}
+          host: ${{ secrets.TYPESENSE_HOST }}
+          port: ${{ secrets.TYPESENSE_PORT }}
+          protocol: ${{ secrets.TYPESENSE_PROTOCOL }}
+          config: docusaurus/docsearch.json
