GROK-10333 GitHub Actions: Check library scope

diff --git a/.github/workflows/libraries.yaml b/.github/workflows/libraries.yaml
--- a/.github/workflows/libraries.yaml
+++ b/.github/workflows/libraries.yaml
@@ -97,6 +97,13 @@ jobs:
       - uses: actions/checkout@v2
         with:
           token: ${{ secrets.WRITE_TOKEN }}
+      - name: Check library properties
+        working-directory: packages/${{ matrix.package }}
+        run: |
+          if [[ "$(jq '.name' package.json | sed -E 's/(^"|"$)//g')" != "@datagrok-libraries/"* ]]; then
+            echo "::error title=${{ matrix.package }}: failed properties check::Library should be in '@datagrok-libraries' scope. Change library name to '@datagrok-libraries/<name>' in ${{ matrix.package }}/package.json"
+            exit 1
+          fi
       - name: Setup Node
         uses: actions/setup-node@v2
         with:
