GitHub Actions: Check packages with grok check

diff --git a/.github/workflows/libraries.yaml b/.github/workflows/libraries.yaml
--- a/.github/workflows/libraries.yaml
+++ b/.github/workflows/libraries.yaml
@@ -105,7 +105,7 @@ jobs:
 
   publish:
     name: Build and publish to npm
-    needs: [metadata, common-check]
+    needs: [ metadata, common-check ]
     if: needs.metadata.outputs.continue == 'yes' && needs.common-check.outputs.continue == 'true'
     runs-on: ubuntu-20.04
     strategy:
@@ -151,6 +151,19 @@ jobs:
       - run: npm run build
         working-directory: libraries/${{ matrix.project }}
         if: ${{ matrix.build == 'true' }}
+      - name: grok check
+        continue-on-error: true
+        run: |
+          grok_check=$(grok check)
+          if grep -q OK <<<$grok_check; then
+            echo "${{ matrix.package }} passes grok check"
+          else
+            echo ${grok_check}
+            echo "::error title=${{ matrix.package }}: failed grok check::${grok_check}"
+            exit 1
+          fi
+        id: grok_check
+        working-directory: packages/${{ matrix.package }}
       - name: npm publish
         run: npm publish --access public
         if: matrix.changed_version == 'true' && github.ref == 'refs/heads/master'
