check notif

diff --git a/.github/workflows/packages.yml b/.github/workflows/packages.yml
--- a/.github/workflows/packages.yml
+++ b/.github/workflows/packages.yml
@@ -561,142 +561,142 @@ jobs:
 #        run: |
 #          npm uninstall -g datagrok-tools@latest
 
-      - name: Publish to npm
-        run: npm publish --access public
-        id: publish
-        working-directory: packages/${{ matrix.package }}
-        env:
-          NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
-        if: matrix.publish == 'publish' && (steps.build.outcome == 'success' || steps.build.outcome == 'skipped') && steps.gen_checks.outcome == 'success' && (steps.check.outcome == 'success' || steps.check.outcome == 'skipped') && steps.install.outcome == 'success' && (steps.test-package.outcome == 'success' || steps.test-package.outcome == 'skipped' || contains(matrix.package, 'Tests'))
+#       - name: Publish to npm
+#         run: npm publish --access public
+#         id: publish
+#         working-directory: packages/${{ matrix.package }}
+#         env:
+#           NODE_AUTH_TOKEN: ${{ secrets.NPM_TOKEN }}
+#         if: matrix.publish == 'publish' && (steps.build.outcome == 'success' || steps.build.outcome == 'skipped') && steps.gen_checks.outcome == 'success' && (steps.check.outcome == 'success' || steps.check.outcome == 'skipped') && steps.install.outcome == 'success' && (steps.test-package.outcome == 'success' || steps.test-package.outcome == 'skipped' || contains(matrix.package, 'Tests'))
 
-      - name: Prepare Slack Message
-        if: ${{ steps.publish.outcome == 'success' && !contains(matrix.package, 'Meta') }}
-        id: slack-prepare
-        shell: bash
-        env:
-          SLACK_ID: ${{ secrets.SLACK_ID }}
-        run: |
-          channel_id=$(echo "$SLACK_ID" | jq -r .\"${{ github.actor }}\")
-          echo "::add-mask::$channel_id"
-          echo SLACK_CHANNEL=$channel_id >> $GITHUB_ENV
+#       - name: Prepare Slack Message
+#         if: ${{ steps.publish.outcome == 'success' && !contains(matrix.package, 'Meta') }}
+#         id: slack-prepare
+#         shell: bash
+#         env:
+#           SLACK_ID: ${{ secrets.SLACK_ID }}
+#         run: |
+#           channel_id=$(echo "$SLACK_ID" | jq -r .\"${{ github.actor }}\")
+#           echo "::add-mask::$channel_id"
+#           echo SLACK_CHANNEL=$channel_id >> $GITHUB_ENV
 
-          header="Package *${{ matrix.package }}* version *${{ matrix.version }}* published to <https://www.npmjs.com/package/$(jq -r .name "packages/${{ matrix.package }}/package.json")/v/${{ matrix.version }}|NPM>"
-          echo SLACK_MESSAGE_HEADER=$header >> $GITHUB_ENV
+#           header="Package *${{ matrix.package }}* version *${{ matrix.version }}* published to <https://www.npmjs.com/package/$(jq -r .name "packages/${{ matrix.package }}/package.json")/v/${{ matrix.version }}|NPM>"
+#           echo SLACK_MESSAGE_HEADER=$header >> $GITHUB_ENV
 
-          context="*GitHub Workflow:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }} ${{ github.run_number }}>\n*Commit:* <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|$(echo "${{ github.sha }}" | cut -c1-8) $(echo -e "${{ github.event.head_commit.message }}" | head -n1 | sed -e 's/"/\\"/g')>"
-          echo SLACK_MESSAGE_CONTEXT=$context >> $GITHUB_ENV
+#           context="*GitHub Workflow:* <${{ github.server_url }}/${{ github.repository }}/actions/runs/${{ github.run_id }}|${{ github.workflow }} ${{ github.run_number }}>\n*Commit:* <${{ github.server_url }}/${{ github.repository }}/commit/${{ github.sha }}|$(echo "${{ github.sha }}" | cut -c1-8) $(echo -e "${{ github.event.head_commit.message }}" | head -n1 | sed -e 's/"/\\"/g')>"
+#           echo SLACK_MESSAGE_CONTEXT=$context >> $GITHUB_ENV
 
-      - name: Send to Slack
-        id: slack
-        if: steps.slack-prepare.outcome == 'success'
-        uses: slackapi/slack-github-action@v1.24.0
-        with:
-          channel-id: ${{ env.SLACK_CHANNEL }}
-          payload: |
-            {
-                "blocks": [
-                    {
-                        "type": "section",
-                        "text": {
-                            "type": "mrkdwn",
-                            "text": "${{ env.SLACK_MESSAGE_HEADER }}"
-                        }
-                    },
-                    {
-                        "type": "context",
-                        "elements": [
-                            {
-                                "type": "mrkdwn",
-                                "text": "${{ env.SLACK_MESSAGE_CONTEXT }}"
-                            }
-                        ]
-                    }
-                ]
-            }
-        env:
-          SLACK_BOT_TOKEN: ${{ secrets.SLACKBOT_TOKEN }}
+#       - name: Send to Slack
+#         id: slack
+#         if: steps.slack-prepare.outcome == 'success'
+#         uses: slackapi/slack-github-action@v1.24.0
+#         with:
+#           channel-id: ${{ env.SLACK_CHANNEL }}
+#           payload: |
+#             {
+#                 "blocks": [
+#                     {
+#                         "type": "section",
+#                         "text": {
+#                             "type": "mrkdwn",
+#                             "text": "${{ env.SLACK_MESSAGE_HEADER }}"
+#                         }
+#                     },
+#                     {
+#                         "type": "context",
+#                         "elements": [
+#                             {
+#                                 "type": "mrkdwn",
+#                                 "text": "${{ env.SLACK_MESSAGE_CONTEXT }}"
+#                             }
+#                         ]
+#                     }
+#                 ]
+#             }
+#         env:
+#           SLACK_BOT_TOKEN: ${{ secrets.SLACKBOT_TOKEN }}
 
-#      - name: Upload Docker image as artifact
-#        if: steps.build-docker.outcome == 'success' && (steps.publish.outcome == 'failure' || steps.publish.outcome == 'skipped')
-#        uses: ishworkh/docker-image-artifact-upload@v1
-#        with:
-#          image: "datagrok/${{ steps.docker_name_ver.outputs.package_name }}:${{ steps.docker_name_ver.outputs.image_ver }}"
+# #      - name: Upload Docker image as artifact
+# #        if: steps.build-docker.outcome == 'success' && (steps.publish.outcome == 'failure' || steps.publish.outcome == 'skipped')
+# #        uses: ishworkh/docker-image-artifact-upload@v1
+# #        with:
+# #          image: "datagrok/${{ steps.docker_name_ver.outputs.package_name }}:${{ steps.docker_name_ver.outputs.image_ver }}"
 
-      - name: Save package Docker image to tar archive
-        if: steps.build-docker.outcome == 'success' && (steps.publish.outcome == 'failure' || steps.publish.outcome == 'skipped')
-        id: save-docker
-        run: |
-          docker save -o /tmp/${{ matrix.package }}.docker.tar ${{ steps.build-docker.outputs.images }}
+#       - name: Save package Docker image to tar archive
+#         if: steps.build-docker.outcome == 'success' && (steps.publish.outcome == 'failure' || steps.publish.outcome == 'skipped')
+#         id: save-docker
+#         run: |
+#           docker save -o /tmp/${{ matrix.package }}.docker.tar ${{ steps.build-docker.outputs.images }}
 
-      - uses: actions/upload-artifact@v4
-        if: steps.save-docker.outcome == 'success'
-        with:
-          path: /tmp/${{ matrix.package }}.docker.tar
-          name: ${{ matrix.package }}.docker.tar
-          retention-days: 14
-          if-no-files-found: warn
+#       - uses: actions/upload-artifact@v4
+#         if: steps.save-docker.outcome == 'success'
+#         with:
+#           path: /tmp/${{ matrix.package }}.docker.tar
+#           name: ${{ matrix.package }}.docker.tar
+#           retention-days: 14
+#           if-no-files-found: warn
 
-#      - name: Build and push package Docker image
-#        if: steps.publish.outcome == 'success' && steps.build-docker.outcome == 'success'
-#        uses: docker/build-push-action@v3
-#        with:
-#          context: packages/${{ matrix.package }}/dockerfiles
-#          push: true
-#          tags: datagrok/${{ steps.docker_name_ver.outputs.package_name }}:${{ steps.docker_name_ver.outputs.image_ver }}
+# #      - name: Build and push package Docker image
+# #        if: steps.publish.outcome == 'success' && steps.build-docker.outcome == 'success'
+# #        uses: docker/build-push-action@v3
+# #        with:
+# #          context: packages/${{ matrix.package }}/dockerfiles
+# #          push: true
+# #          tags: datagrok/${{ steps.docker_name_ver.outputs.package_name }}:${{ steps.docker_name_ver.outputs.image_ver }}
 
-      - name: Publish package Docker image
-        if: steps.publish.outcome == 'success' && steps.build-docker.outcome == 'success'
-        id: publish-docker
-        run: |
-          for image in $(echo -e ${{ steps.build-docker.outputs.images }}); do
-            docker push $image
-          done
+#       - name: Publish package Docker image
+#         if: steps.publish.outcome == 'success' && steps.build-docker.outcome == 'success'
+#         id: publish-docker
+#         run: |
+#           for image in $(echo -e ${{ steps.build-docker.outputs.images }}); do
+#             docker push $image
+#           done
 
-      - name: Commit package-lock.json
-        id: git
-        continue-on-error: true
-        if: steps.publish.outcome == 'success' || steps.package-lock.outcome == 'success'
-        run: |
-          git config --global user.name 'github-actions[bot]'
-          git config --global user.email 'github-actions[bot]@users.noreply.github.com'
-          git pull
-          continue=false
-          if [ -n "$(git status -s packages/${{ matrix.package }}/package-lock.json)" ]; then
-            git add packages/${{ matrix.package }}/package-lock.json
-            skip_ci=""
-            if [ ${{ github.ref }} == 'refs/heads/master' ]; then
-              skip_ci="[skip ci]"
-            fi
-            git commit -m "GitHub Actions: Update packages/${{ matrix.package }}/package-lock.json $skip_ci
+#       - name: Commit package-lock.json
+#         id: git
+#         continue-on-error: true
+#         if: steps.publish.outcome == 'success' || steps.package-lock.outcome == 'success'
+#         run: |
+#           git config --global user.name 'github-actions[bot]'
+#           git config --global user.email 'github-actions[bot]@users.noreply.github.com'
+#           git pull
+#           continue=false
+#           if [ -n "$(git status -s packages/${{ matrix.package }}/package-lock.json)" ]; then
+#             git add packages/${{ matrix.package }}/package-lock.json
+#             skip_ci=""
+#             if [ ${{ github.ref }} == 'refs/heads/master' ]; then
+#               skip_ci="[skip ci]"
+#             fi
+#             git commit -m "GitHub Actions: Update packages/${{ matrix.package }}/package-lock.json $skip_ci
 
-            Workflow ${{ github.workflow }} ${{ github.run_number }}
-            https://github.com/datagrok-ai/public/actions/runs/${{ github.run_id }}"
-            continue=true
-          fi
-          if [[ "${continue}" == "true" ]]; then
-            count=0
-            retries=10
-            until git push; do
-              exit=$?
-              wait=$((2 ** count))
-              count=$((count + 1))
-              if [ $count -lt "$retries" ]; then
-                echo "Retry $count/$retries exited $exit, retrying 'git push' in $wait seconds..."
-                sleep $wait
-                git pull --rebase
-              else
-                echo "Retry $count/$retries exited $exit, no more retries left for 'git push'."
-                exit $exit
-              fi
-            done
-          fi
+#             Workflow ${{ github.workflow }} ${{ github.run_number }}
+#             https://github.com/datagrok-ai/public/actions/runs/${{ github.run_id }}"
+#             continue=true
+#           fi
+#           if [[ "${continue}" == "true" ]]; then
+#             count=0
+#             retries=10
+#             until git push; do
+#               exit=$?
+#               wait=$((2 ** count))
+#               count=$((count + 1))
+#               if [ $count -lt "$retries" ]; then
+#                 echo "Retry $count/$retries exited $exit, retrying 'git push' in $wait seconds..."
+#                 sleep $wait
+#                 git pull --rebase
+#               else
+#                 echo "Retry $count/$retries exited $exit, no more retries left for 'git push'."
+#                 exit $exit
+#               fi
+#             done
+#           fi
 
-      - name: Trigger help update
-        continue-on-error: true
-        if: steps.publish.outcome == 'success'
-        run: gh workflow run docusaurus.yaml --ref ${{ github.ref }}
-        env:
-          GH_TOKEN: ${{ github.token }}
+#       - name: Trigger help update
+#         continue-on-error: true
+#         if: steps.publish.outcome == 'success'
+#         run: gh workflow run docusaurus.yaml --ref ${{ github.ref }}
+#         env:
+#           GH_TOKEN: ${{ github.token }}
       
       - name: Slack Notification
         if: always()
