GROK-10485 GitHub Actions: package test output result

diff --git a/.github/workflows/packages_test.yml b/.github/workflows/packages_test.yml
--- a/.github/workflows/packages_test.yml
+++ b/.github/workflows/packages_test.yml
@@ -111,8 +111,10 @@ jobs:
       - name: Test Package
         id: test-package
         run: |
-          npm run test -- --verbose=false || echo \
-            "::error file=packages/${{ matrix.package }},title=Package ${{ matrix.package }} failed tests::Check ${{ matrix.package }}-test-report-${{ github.sha }}.html report for results"
+          npm run test -- --verbose=false || {
+            echo "::error file=packages/${{ matrix.package }},title=Package ${{ matrix.package }} failed tests::Check ${{ matrix.package }}-test-report-${{ github.sha }}.html report for results";
+            echo "::set-output name=status::error";
+          }
         env:
           JEST_HTML_REPORTER_PAGE_TITLE: "${{ matrix.package }} Test Report. Commit ${{ github.sha }}."
           JEST_HTML_REPORTER_OUTPUT_PATH: "./${{ matrix.package }}-test-report-${{ github.sha }}.html"
